config/routes.rb
ComeFindMe::Application.routes.draw do

  get 'signup', to: 'users#new', as: 'signup'
  post 'signup', to: 'users#create'
  get 'login', to: 'sessions#new', as: 'login'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy', as: 'logout'

  resources :broadcasts

  resources :locations do
    get 'broadcasts', :to => 'broadcasts#location_broadcasts', :on => :member
  end

  resources :messages do
    get 'broadcasts', :to => 'broadcasts#message_broadcasts', :on => :member
  end

  resources :password_resets

  resources :sessions

  resources :sync, :only => [ :index ]
  get "sync/from/:from_date", :to => "sync#index"

  resources :users, :except => :index

  root 'sessions#new'
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ComeFindMe</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div>
    <%= link_to :broadcasts, broadcasts_path %>
    <%= link_to :locations, locations_path %>
    <%= link_to :messages, messages_path %>
    <%= link_to :sync, sync_index_path %>
    <% if current_user %>
      Logged in as <%= link_to current_user.facebook_id, user_path(current_user) %> 
      <%= link_to "Log Out", logout_path, method: "delete" %>
    <% else %>
      <%= link_to 'Sign Up', signup_path %> or 
      <%= link_to "Log In", login_path %>
    <% end %>
  </div>

  <% flash.each do |name, msg| %>
    <%= content_tag :div, msg, id: "flash_#{name}" %>
  <% end %>

  <%= yield %>

</body>
</html>